theme: jekyll-theme-minimal
layout: full
title: Michael Richter CV
description: My resume
show_downloads: False
navigation:
  - title: Curiculum Vitae
    url: /
  - title: Cover Letter
    url: cover_letter
